#if !canImport(ObjectiveC)
import XCTest

extension EncodingErrorTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodingErrorTests = [
        ("testKeyedContainer", testKeyedContainer),
        ("testSingleValueContainer", testSingleValueContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EncodingErrorTests.__allTests__EncodingErrorTests),
    ]
}
#endif
